apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ibou1984/ecommerce_project-backend:latest
          ports:
            - containerPort: 8000
          env:
            # Variables d'environnement si nécessaires pour Django
            - name: DJANGO_SETTINGS_MODULE
              value: ecommerce_project.settings
            - name: DATABASE_URL
              value: postgres://user:password@postgres:5432/dbname
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
