apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ecommerce
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ecommerce_project-backend:latest
        imagePullPolicy: Never  # Pour utiliser l'image locale
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: DJANGO_SETTINGS_MODULE
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: DEBUG
        - name: ALLOWED_HOSTS
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: ALLOWED_HOSTS
        - name: CORS_ALLOWED_ORIGINS
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: CORS_ALLOWED_ORIGINS
        - name: CORS_ALLOW_ALL_ORIGINS
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: CORS_ALLOW_ALL_ORIGINS
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: ecommerce-secret
              key: SECRET_KEY
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: ecommerce-secret
              key: DATABASE_URL
        - name: REDIS_URL
          value: "redis://redis-service:6379/0"
        volumeMounts:
        - name: media-storage
          mountPath: /app/media
        - name: static-storage
          mountPath: /app/static
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: media-storage
        persistentVolumeClaim:
          claimName: ecommerce-media-pvc
      - name: static-storage
        persistentVolumeClaim:
          claimName: ecommerce-static-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: ecommerce
spec:
  selector:
    app: backend
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP 